// <auto-generated />
namespace DevStats.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreateReleaseQualityReport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateReleaseQualityReport));
        
        string IMigrationMetadata.Id
        {
            get { return "201711170845217_CreateReleaseQualityReport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
